/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'rich-black': '#212121',
        'ice-blue': '#EAEFF5',
        'pure-white': '#FFFFFF',
        surface: '#FFFFFF',
        'surface-dim': '#d5dae0',
        'surface-bright': '#FFFFFF',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4fa',
        'surface-container': '#e9eef4',
        'surface-container-high': '#e4e9ef',
        'surface-container-highest': '#dee3e9',
        'on-surface': '#212121',
        'on-surface-variant': '#444748',
        'inverse-surface': '#2b3136',
        'inverse-on-surface': '#ecf1f7',
        outline: '#747878',
        'outline-variant': '#c4c7c7',
        'surface-tint': '#5f5e5e',
        primary: '#212121',
        'on-primary': '#ffffff',
        'primary-container': '#212121',
        'on-primary-container': '#898888',
        'inverse-primary': '#c8c6c5',
        'primary-fixed': '#e5e2e1',
        'primary-fixed-dim': '#c8c6c5',
        'on-primary-fixed': '#1b1c1c',
        'on-primary-fixed-variant': '#474746',
        secondary: '#595f64',
        'on-secondary': '#ffffff',
        'secondary-container': '#dbe0e6',
        'on-secondary-container': '#5e6368',
        'secondary-fixed': '#dee3e9',
        'secondary-fixed-dim': '#c2c7cd',
        'on-secondary-fixed': '#212121',
        'on-secondary-fixed-variant': '#42474c',
        tertiary: '#080a0a',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#1f2121',
        'on-tertiary-container': '#878889',
        'tertiary-fixed': '#e2e2e2',
        'tertiary-fixed-dim': '#c6c6c7',
        'on-tertiary-fixed': '#1a1c1c',
        'on-tertiary-fixed-variant': '#454747',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        background: '#EAEFF5',
        'on-background': '#212121',
        'surface-variant': '#dee3e9',
      },
      fontFamily: {
        sans: ['Hanken Grotesk', 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'],
        helvetica: ['Hanken Grotesk', 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'],
        'headline-xl': ['Hanken Grotesk', 'sans-serif'],
        'headline-lg': ['Hanken Grotesk', 'sans-serif'],
        'headline-md': ['Hanken Grotesk', 'sans-serif'],
        'headline-xl-mobile': ['Hanken Grotesk', 'sans-serif'],
        'display-hero': ['Hanken Grotesk', 'sans-serif'],
        'label-caps': ['Hanken Grotesk', 'sans-serif'],
        caption: ['Hanken Grotesk', 'sans-serif'],
        'body-lg': ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'display-hero': ['400px', { lineHeight: '360px', letterSpacing: '-0.04em', fontWeight: '200' }],
        'headline-xl': ['160px', { lineHeight: '144px', letterSpacing: '-0.03em', fontWeight: '700' }],
        'headline-xl-mobile': ['64px', { lineHeight: '60px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['86px', { lineHeight: '90px', letterSpacing: '-0.01em', fontWeight: '300' }],
        'headline-md': ['42px', { lineHeight: '48px', letterSpacing: '0em', fontWeight: '600' }],
        'label-caps': ['14px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '600' }],
        caption: ['16px', { lineHeight: '20px', fontWeight: '400' }],
        'body-lg': ['21px', { lineHeight: '32px', fontWeight: '400' }],
      },
      spacing: {
        'container-max': '1920px',
        'edge-margin': '60px',
        gutter: '24px',
        'section-gap': '200px',
        'stack-sm': '8px',
        'stack-md': '24px',
        'stack-lg': '48px',
      },
      maxWidth: {
        'container-max': '1920px',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '1rem',
        xl: '1.5rem',
        full: '9999px',
      },
    },
  },
  plugins: [],
}
